"""Initial migration for users and detections tables

Revision ID: 5b7da8d4764f
Revises: 
Create Date: 2026-08-16 23:28:54.425473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b7da8d4764f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('result', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ai_probability', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('real_probability', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('frames_analyzed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suspicious_frames', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_detections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('detections_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('prediction')
        batch_op.drop_column('metadata_info')
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metadata_info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prediction', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detections_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_detections_user_id'))
        batch_op.drop_index(batch_op.f('ix_detections_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('suspicious_frames')
        batch_op.drop_column('frames_analyzed')
        batch_op.drop_column('real_probability')
        batch_op.drop_column('ai_probability')
        batch_op.drop_column('result')
        batch_op.drop_column('media_type')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
